### ISSUE TITLE
Wheel support

### ISSUE THREAD

**Issue by kevin-brown** [core-api/python-client#104]
http://pythonwheels.com/

Right now, only the `tar.gz` file is being distributed on PyPI for [coreapi](https://pypi.python.org/pypi/coreapi), which isn't _that much_ of an issue, but it does add some time to installing the package.

This package should be compatible with the Wheel format, considering it doesn't appear to have any C dependencies and it is compatible with both Python 2 and 3. As a result, you should only need to generate a universal wheel and then everyone (on all systems) will get the ability to install coreapi with just the wheel, without having to do any extra work.
---

Note that this also applies to all of the other Core API modules which are published as Python packages.

**Comment by tomchristie** [comment]
Sounds good yup.
Forgotten exactly what hoops we need to jump through in order to provide this, so PR's welcome! 😃
