### ISSUE TITLE
tempfile._TemporaryFileWrapper not available under Google Appengine

### ISSUE THREAD

**Issue by cdman** [core-api/python-client#106]
Google appengine replaces the tempfile module with a custom one (since you can't write to the FS under "traditional" GAE): https://code.google.com/p/googleappengine/source/browse/trunk/python/google/appengine/dist/tempfile.py

However this module lacks the `_TemporaryFileWrapper` on which `utils.DownloadedFile` is based: https://github.com/core-api/python-client/blob/master/coreapi/utils.py#L119

Given that `_TemporaryFileWrapper` is an undocumented API (class) IMHO the dependency on it should be removed.

**Comment by tomchristie** [comment]
👍  Good call.

**Comment by tomchristie** [comment]
Worth noting that even when we do resolve this, the `DownloadCodec` still wouldn't work under GAE, but that's much less of a concern. (Ie. at least everything else will work.)

**Comment by canthonyscott** [comment]
Is there any workaround for this? I am trying to deploy an app to the Google App Engine standard python environment and this is causing Django to crash on load. 

For the record everything works fine in the GAE flexible environment, but not in the standard environment.

**Comment by cdman** [comment]
It seems to me that rather than using `_TemporaryFileWrapper`, we should use [NamedTemporaryFile](https://docs.python.org/2/library/tempfile.html#tempfile.NamedTemporaryFile) - which is a function, not a class. This would "work" on GAE in the sense that the module would load (but calling it would still raise a NotImplementedError).

**Comment by tomchristie** [comment]
Hoping to look into resolving this sometime over the next few days.
Pull requests welcome in the meantime.

**Comment by tomchristie** [comment]
Okay, that should be resolved now. If anyone wants to confirm that'd be fab.
