### ISSUE TITLE
JSON encoding is broken with Requests v2.8.0

### ISSUE THREAD

**Issue by liavkoren** [core-api/python-client#118]
2.8.0 has a bug, [(fixed in v2.8.1)](https://pypi.python.org/pypi/requests/#id14) that broke JSON encoding when using [`session.prepare_request`](https://github.com/core-api/python-client/blob/master/coreapi/transports/http.py#L186). 

Perhaps the requirements should be updated to exclude that version?

**Comment by tomchristie** [comment]
Given that 2.8.0 is no longer current I'm disinclined to patch our setup requirements around it.

Worth asking tho, thanks!
