### ISSUE TITLE
Creating Document Fields restricted to a list of values

### ISSUE THREAD

**Issue by xennygrimmato** [core-api/python-client#123]
I want to create an enumerated list of values that are allowed for a Field object.
Does the Python client currently allow this?

As per [this page in the Documentation](http://core-api.github.io/python-client/api-guide/document/), I don't see an option such as `enum` or anything else to do this.

Eventually, I would like to see a dropdown of these values on my Swagger UI.

**Comment by tomchristie** [comment]
Support for schemas on fields does exist but isn't yet documented.
You'd do something like this...

    `schema=coreschema.Enum([...])`

However keep in mind that the python client *does not (currently?) enforce client-side validation* - you need to enforce that server side.

**Comment by xennygrimmato** [comment]
Would that create a dropdown on a Swagger UI front-end?
My Field object looks like this currently:
```
coreapi.Field(
                            name="feedback",
                            required=True,
                            location="query",
                            description="Feedback type",
                            schema=coreschema.Enum([0,1,2])
                        )
```
This, however, doesn't show a drop-down list on the Swagger UI. Is support available for rendering these values as a dropdown on swagger?

**Comment by tomchristie** [comment]
Yes, it would. Tho our swagger codec has some catching up to do before that'll work.

**Comment by xennygrimmato** [comment]
Where can I contribute to do the required catching up to make it work?
