### ISSUE TITLE
Unable to specify arbitrary query parameters

### ISSUE THREAD

**Issue by lwm** [core-api/python-client#141]
I have a paginated web API end-point, that expects `?limit=foo`, when I run:

``` python
client.action(schema, actions, params={'limit':200})
```

I see:

```
Traceback (most recent call last):
  File "timeseries.py", line 11, in <module>
    response = client.action(schema, actions, params={"limit": 2000})
  File "/home/lwm/.local/share/virtualenvs/carbondoomsday-IdcgiUO9/lib/python3.5/site-packages/coreapi/client.py", line 165, in action
    _validate_parameters(link, params)
  File "/home/lwm/.local/share/virtualenvs/carbondoomsday-IdcgiUO9/lib/python3.5/site-packages/coreapi/client.py", line 80, in _validate_parameters
    raise exceptions.ParameterError(errors)
coreapi.exceptions.ParameterError: {'limit': 'Unknown parameter.'}
```

Something I'm doing wrong or?

**Comment by asmith-pgdx** [comment]
Are you using Django REST Framework?  If so, this appears to be an issue with DRF 3.6.3, specifically with pagination query parameters.  A change between 3.6.2 and 3.6.3 allows for the possibility that:

1. pagination is disabled but appears in the schema, or
2. pagination is enabled but doesn't appear in the schema (leading to the error you're seeing)

See:
https://github.com/encode/django-rest-framework/issues/5144
https://github.com/encode/django-rest-framework/issues/5168

**Comment by erfan-mehraban** [comment]
temporary solutions is override ```_validate_parameters``` method and make it skip this validation!

**Comment by erfan-mehraban** [comment]
you can make client to skip validation:
```
client.action(schema, actions, params={'limit':200}, validate=False)
```
or somehow override ```coreapi.client._validate_parameters```

**Comment by decentral1se** [comment]
Thanks both, this looks fixed from the two DRF tickets (yes, was using that), I will close!
