### ISSUE TITLE
Unable to specify type for list elements

### ISSUE THREAD

**Issue by gitstercode** [core-api/python-client#148]
For Open-api specification, I am trying to specify type of list elements as Integer, but thats not affecting the default value "string".

I want some thing like this:     
{
  "admin": 0,
  "members": [ 0 ]
}

But I am getting:
{
  "admin": 0,
  "members": [ "string"]
}

Based on below specs.

`
'user_access': {
                    'add': coreapi.Link(
                        '/user/access/add/', action='post',
                        fields=[
                            coreapi.Field(name='admin', schema=coreschema.Integer()),
                            coreapi.Field(name='members', schema=coreschema.Array( type=coreschema.Integer() 
),
                        ]
                    )
}
`

**Comment by tomchristie** [comment]
Better OpenAPI support is coming in 3.0. Feel free to re-raise this is this is still an issue after that release.
