### ISSUE TITLE
HTTPTransport ignores credentials

### ISSUE THREAD

**Issue by quantumkoen** [core-api/python-client#151]
Using coreapi-cli, JWT authentication failed for me:

```$ coreapi credentials add localhost "JWT `curl -s -d "username=user&password=pass" http://localhost:8000/jwt/ | cut -d\\\" -f 4`"
$ coreapi get --debug http://localhost:8000/schema
> GET /schema HTTP/1.1
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> Accept: application/coreapi+json, application/vnd.coreapi+json, */*
> Host: localhost
> User-Agent: coreapi
< 301 Moved Permanently
< Content-Length: 0
< Content-Type: text/html; charset=utf-8
< Date: Fri, 05 Jan 2018 14:54:47 GMT
< Location: /schema/
< Server: WSGIServer/0.2 CPython/3.5.2

....```

No ```Authorization``` header was sent.

I figured out this line was incorrect:

https://github.com/core-api/python-client/blob/master/coreapi/transports/http.py#L352

Changing it to ```session.auth = DomainCredentials(credentials)``` fixed it for me.

**Comment by quantumkoen** [comment]
Oh, looks like there is already a PR for this: https://github.com/core-api/python-client/pull/146/files

**Comment by tomchristie** [comment]
Upgrade to the latest `coreapi-cli` which no longer uses the deprecated `credentials`.
Sorry this took so long to address!
