### ISSUE TITLE
Proxy settings in session instances not honored.

### ISSUE THREAD

**Issue by palbee** [core-api/python-client#158]
When creating a client with a request.Sessions instance the proxies field is ignored. While proxies may be configured via environment variables, they should also be configurable via session objects.

**Comment by tomchristie** [comment]
Can you give me an example of what we'd need to change to support this?

**Comment by tomchristie** [comment]
Okay, this should be fixed in master, and the upcoming 3.0 release. (We use `session.request` now, rather than building the request then sending it)
