### ISSUE TITLE
Remove dependency on itypes or take over maintenance

### ISSUE THREAD

**Issue by edmorley** [core-api/python-client#163]
Hi!

The itypes dependency doesn't appear to be actively maintained (eg tomchristie/itypes#9).
Could core-api either fork it/take over ownership or else remove the dependency on it?

Many thanks :-)

**Comment by tomchristie** [comment]
We’ll be removing the dependency on it in the upcoming version, which is partly why I’ve not been active there.

**Comment by edmorley** [comment]
Makes sense, thank you :-)
