### ISSUE TITLE
base_url not used by codec.load() if url supplied by schema

### ISSUE THREAD

**Issue by mnoky** [core-api/python-client#90]
Hi, I've been using the coreapi client by reading a schema file something like this:

```
input_file = open(filename, 'rb')
input_bytes = input_file.read()
input_file.close()
codec = codecs.CoreJSONCodec()
base_url="http://localhost:9090"  # override base_url for testing
doc = codec.load(input_bytes, base_url=base_url)
```

Note that the url is already supplied in the schema file. I would expect that the `base_url` parameter would override the url provided in the schema, but it does not. Is this by design? The `base_url` parameter is not documented. If this behavior is by design, what is the mechanism by which one can override the url of the server? (say, for testing a client against an alternate server)

**Comment by tomchristie** [comment]
The CoreJSON spec documents this here: http://www.coreapi.org/specification/encoding/#document

If the CoreJSON encoding includes a url then that is used as the URL of the document. If it does not then the URL from which it was requested may be used.

The way to handle this is to ensure that the server sets the URL of the document appropriately. Eg don't set it at all development (allow whatever host/port it's being run on), and only set it to the canonical API url in staging/production environments.

**Comment by mnoky** [comment]
Thanks Tom. Yes, I read that spec and regarding the document url it states "[the url property] MAY be considered a default value by client libraries". It wasn't clear to me if the intention of the python client was to allow the schema-provided url to be overridden or not using `base_url` (apparently not). So, in my case it is easy enough to just omit the url from the schema. Then, clients can choose whichever server is appropriate (e.g. test, staging, production, etc).

BTW, really loving this whole framework! Very clean and lightweight. On the client side, I love how I can use `requests` transport adapters to customize connections (setting CA bundle, setting up timeouts, etc). Previously used swagger generated clients where that was not possible without modifying the generated code, not very maintainable :)

**Comment by tomchristie** [comment]
> BTW, really loving this whole framework! Very clean and lightweight. On the client side, I love how I can use requests transport adapters to customize connections (setting CA bundle, setting up timeouts, etc). Previously used swagger generated clients where that was not possible without modifying the generated code, not very maintainable :)

Great! I've been really excited by it, so it's really good to hear positive feedback about it.
